# Feature Extration

#### using the already existing data on the dataset to create new more meaning ful data to help predict better model

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.head(3)

,customer_id,name,age,gender,signup_date,last_purchase_date,total_purchases,total_spent,country,email,device_type,is_subscribed,feedback_score
0,9042c717-0fd5-4581-a027-91d9758eaca8,George Jones,19,Female,2023-05-17,2024-04-02,18,8864.01,Turkey,georgejones12@example.com,Mobile,0,1.4
1,b6f7fde5-4473-470f-a419-153fd25fd8f1,William Nelson,56,Male,2023-02-12,2025-05-09,29,5445.59,India,williamnelson1@example.org,Desktop,1,2.1
2,e997aecb-5427-469a-a0c5-59a9e417f31d,Jennifer Young,24,Male,2022-07-18,2025-01-05,109,4193.07,India,jenniferyoung6@example.com,Mobile,0,4.9

In [4]:
df.shape

(100, 13)

In [5]:
df.dtypes

customer_id            object
name                   object
age                     int64
gender                 object
signup_date            object
last_purchase_date     object
total_purchases         int64
total_spent           float64
country                object
email                  object
device_type            object
is_subscribed           int64
feedback_score        float64
dtype: object

In [6]:
bins = [10,30,50,70]
labels = ["young","mid","senior"]

#### a new column is cut from column age where bins is seperated values to group and label is labelling them 10, 30, 50, 70 are the values where 10 is young, 30 and 50 is mid and 70 is senior

In [7]:
df["age_group"] = pd.cut(df["age"], bins = bins, labels = labels)

In [8]:
df[["age","age_group"]].head()

   age age_group
0   19     young
1   56    senior
2   24     young
3   53    senior
4   47       mid

In [9]:
df['signup_date'] = pd.to_datetime(df['signup_date'])
df['last_purchase_date'] = pd.to_datetime(df['last_purchase_date'])

In [10]:
df.dtypes

customer_id                   object
name                          object
age                            int64
gender                        object
signup_date           datetime64[ns]
last_purchase_date    datetime64[ns]
total_purchases                int64
total_spent                  float64
country                       object
email                         object
device_type                   object
is_subscribed                  int64
feedback_score               float64
age_group                   category
dtype: object

#### converted into dateandtime datatype and extract year and month from dataset to create new columns and use todays date and signin date to find the total date for sign in same with last purchase this shows how long the customer hasnt purchased anything

In [11]:
df['signup_year'] = df['signup_date'].dt.year
df['signup_month'] = df['signup_date'].dt.month

df['date_since_signin'] = (pd.Timestamp.today() - df['signup_date']).dt.days
df['date_since_lastpur'] = (pd.Timestamp.today() - df['last_purchase_date']).dt.days
print(df['date_since_signin'].head(3))
print(df['date_since_lastpur'].head(3))

0    1033
1    1127
2    1336
Name: date_since_signin, dtype: int64
0    712
1    310
2    434
Name: date_since_lastpur, dtype: int64

#### apply lamba function from start to end split the values and 0 means select the first word and label as name and -1 is label for last values which is now name lastname and length of name

In [12]:
df['first_name'] = df['name'].apply(lambda x:x.split()[0])
df['last_name'] = df['name'].apply(lambda x:x.split()[-1])
df['length_name'] = df['name'].apply(len)
print(df['first_name'].head(3))
print(df['last_name'].head(3))
print(df['length_name'].head(3))

0      George
1     William
2    Jennifer
Name: first_name, dtype: object
0     Jones
1    Nelson
2     Young
Name: last_name, dtype: object
0    12
1    14
2    14
Name: length_name, dtype: int64

#### if the total spend of custon=mer is more then 5000 then theu are high spender which is 1 and if its low it will be 0|

In [13]:
df['high_spender'] = (df['total_spent'] > 5000).astype(int)
print(df['high_spender'])

0     1
1     1
2     0
3     0
4     0
     ..
95    1
96    0
97    1
98    1
99    0
Name: high_spender, Length: 100, dtype: int64

In [14]:
df

,customer_id,name,age,gender,signup_date,last_purchase_date,total_purchases,total_spent,country,email,...,feedback_score,age_group,signup_year,signup_month,date_since_signin,date_since_lastpur,first_name,last_name,length_name,high_spender
0,9042c717-0fd5-4581-a027-91d9758eaca8,George Jones,19,Female,2023-05-17,2024-04-02,18,8864.01,Turkey,georgejones12@example.com,...,1.4,young,2023,5,1033,712,George,Jones,12,1
1,b6f7fde5-4473-470f-a419-153fd25fd8f1,William Nelson,56,Male,2023-02-12,2025-05-09,29,5445.59,India,williamnelson1@example.org,...,2.1,senior,2023,2,1127,310,William,Nelson,14,1
2,e997aecb-5427-469a-a0c5-59a9e417f31d,Jennifer Young,24,Male,2022-07-18,2025-01-05,109,4193.07,India,jenniferyoung6@example.com,...,4.9,young,2022,7,1336,434,Jennifer,Young,14,0
3,6522d7c2-bcef-48f9-b0d6-2fd8e7b4ef0d,Christopher Williams,53,Male,2024-01-11,2024-01-29,91,927.71,Brazil,christopherwilliams99@example.net,...,4.5,senior,2024,1,794,776,Christopher,Williams,20,0
4,d6ebe5ab-14e2-4b64-b1eb-1ad16df6e854,Christopher Harris,47,Female,2024-01-18,2023-11-30,48,4327.72,India,christopherharris90@example.com,...,3.1,mid,2024,1,787,836,Christopher,Harris,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,25d558a8-f749-4951-a563-f2b6f5ac2bef,Thomas White,41,Other,2024-08-29,2023-05-18,12,9998.09,Russian Federation,thomaswhite56@example.org,...,4.2,mid,2024,8,563,1032,Thomas,White,12,1
96,1309bf9c-84cb-4a82-8b1e-f93063843c5d,Sharon Nolan,55,Other,2025-02-24,2024-11-06,86,1554.55,Australia,sharonnolan86@example.net,...,4.9,senior,2025,2,384,494,Sharon,Nolan,12,0
97,e6851716-3746-4dec-ad58-8bb493e2199d,Steven Martin,40,Male,2024-11-05,2024-03-11,20,7915.16,Brazil,stevenmartin14@example.net,...,1.5,mid,2024,11,495,734,Steven,Martin,13,1
98,4085aa51-9d37-47a4-9d41-721f4b4e7f94,Karen Campbell,32,Female,2025-02-22,2023-02-23,78,11156.10,India,karencampbell4@example.org,...,4.7,mid,2025,2,386,1116,Karen,Campbell,14,1
99,15aaa7cb-b48c-4a53-8975-688a3e5480f4,Charles Miller,29,Female,2025-03-05,2025-03-31,9,1788.31,Bangladesh,charlesmiller12@example.com,...,2.7,young,2025,3,375,349,Charles,Miller,14,0