# Feature Scaler

## Importing Required Library

We first import the **Pandas** library, which is used for data manipulation and analysis in Python.

```python
import pandas as pd

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('featureeng.csv')

In [4]:
df.head(3)

,Age,Salary,YearsExperience,NumCertifications,JobSatisfaction,JobTitle,Education,City,Promotion
0,28,132612,9,2,1,Data Engineer,High School,Seattle,Got Promotion
1,41,116641,8,4,3,Data Scientist,Master's,Chicago,No Promotion
2,36,113811,11,1,6,Web Developer,PhD,Chicago,Got Promotion

### Importing Scalers

We import two scaling techniques from `sklearn.preprocessing`:

- **StandardScaler** – Standardizes features by removing the mean and scaling to unit variance.
- **MinMaxScaler** – Scales features to a fixed range (usually 0 to 1).

In [6]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [7]:
standardscaler = StandardScaler()

In [ ]:
df['salarystdscaler'] = standardscaler.fit_transform(df[['Salary']])

In [10]:
minmax = MinMaxScaler()

In [11]:
df['salaryminmax'] = minmax.fit_transform(df[['Salary']])

In [12]:
df[['Salary','salarystdscaler','salaryminmax']].head()

   Salary  salarystdscaler  salaryminmax
0  132612         0.642403      0.666000
1  116641        -0.023380      0.471232
2  113811        -0.141354      0.436720
3  102160        -0.627049      0.294634
4  101313        -0.662358      0.284305

In [13]:
df[['Salary','salarystdscaler','salaryminmax']].describe()

              Salary  salarystdscaler  salaryminmax
count      20.000000     2.000000e+01     20.000000
mean   117201.850000    -2.331468e-16      0.478071
std     24611.481966     1.025978e+00      0.300140
min     78000.000000    -1.634207e+00      0.000000
25%    100609.750000    -6.916745e-01      0.275729
50%    115226.000000    -8.236722e-02      0.453976
75%    135750.000000     7.732164e-01      0.704268
max    160000.000000     1.784126e+00      1.000000